language: node_js
node_js:
  - lts/*

script:
  - npm install
  - npm build

deploy:
  local_dir: public
  fqdn: airwindowscheatsheet.aboni.dev
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
  branch: master
